# ArgoCD Application for CCB (Public Repo)
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ccb-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yassinshaher1/CCB.git
    targetRevision: main
    path: k8s-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: ccb-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
